services:
  web:
    image: ${DOCKER_IMAGE}:production
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - ${NETWORK_NAME}
    environment:
      - NODE_ENV=production
      - DEBUG=false
    volumes:
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  ${NETWORK_NAME}:
    driver: bridge