version: '3.8'

services:
  web:
    image: ikenna2025/final-project:production
    ports:
      - "83:80"
    environment:
      - NODE_ENV=production
      - DEBUG=false
    volumes:
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
