version: '3.8'

services:
  web:
    image: ${DOCKER_IMAGE}:development
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - DEBUG=true
    volumes:
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge